name: 'Rollout restart deployment'
description: 'Rollout restart deployment'
author: 'Feavy'
runs:
    using: composite
    steps:
      - run: |
          if [[ -n "$FILE_PATH" || -n "$YAML_PATH" || -n "$TAG" ]] ; then
            BODY='{"namespace":"'$NAMESPACE'","deployment":"'$DEPLOYMENT'","filePath":"'$FILE_PATH'","yamlPath":"'$YAML_PATH'","tag":"'$TAG'"}'
          else
            BODY='{"namespace":"'$NAMESPACE'","deployment":"'$DEPLOYMENT'"}'
          fi
          curl -X POST "https://controller.feavy.fr/deploy" -H "Authorization: Bearer $BEARER_TOKEN" -v -H "Content-type: application/json" --data "$BODY"
        shell: bash
