name: 'Rollout restart deployment'
description: 'Rollout restart deployment'
author: 'Feavy'
runs:
    using: composite
    steps:
      - run: |
          curl -X POST "https://controller.feavy.fr/restart" -H "Authorization: Bearer $BEARER_TOKEN" -v -H "Content-type: application/json" --data '{"namespace":"'$NAMESPACE'","deployment":"'$DEPLOYMENT'"}'
        shell: bash
